# General properties
#binance:
#server.host: 0.0.0.0
rate: 20000
exchange: org.knowm.xchange.binance.BinanceExchange
symbols:
        - ETH/BTC
        - LTC/BTC
        - XRP/BTC
        - BTG/BTC

# Spring Boot
